- name: Check if tfenv is installed
  shell: test -d ~/.tfenv && echo "yes" || echo "no"
  register: is_tfenv_installed

- name: Clone tfenv
  git:
    repo: 'https://github.com/tfutils/tfenv.git'
    dest: ~/.tfenv
  when: is_tfenv_installed.stdout == "no"

- name: Install & Set Terraform Version
  shell: |
      ~/.tfenv/bin/tfenv install {{ terraform_version }}
      ~/.tfenv/bin/tfenv use {{ terraform_version }}
  vars:
    terraform_version: 1.3.6

- name: Install terraform-ls (x86_64)
  get_url:
    url: https://releases.hashicorp.com/terraform-ls/{{ terraform_ls_version }}/terraform-ls_{{ terraform_ls_version }}_linux_amd64.zip
    dest: ~/bin/terraform/terraform-ls.zip
  vars:
    terraform_ls_version: 0.30.1
  when: ansible_architecture == "x86_64"

- name: Install terraform-ls (aarch64)
  get_url:
    url: https://releases.hashicorp.com/terraform-ls/{{ terraform_ls_version }}/terraform-ls_{{ terraform_ls_version }}_linux_arm64.zip
    dest: ~/bin/terraform/terraform-ls.zip
  vars:
    terraform_ls_version: 0.30.1
  when: ansible_architecture == "aarch64"

- name: Unzip terraform-ls
  unarchive:
    src: ~/bin/terraform/terraform-ls.zip
    dest: ~/bin
    remote_src: yes
  register: terraform_ls_unzip
