- name: Add an apt signing key for Helm
  become: true
  get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    dest: /usr/share/keyrings/helm.asc
    mode: '0644'

- name: Add Helm Repository
  become: true
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/helm.asc] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main
    state: present
    filename: helm-stable-debian

- name: Install Helm
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - helm

- name: Install Helm plugins
  become: true
  command: helm plugin install {{ item }}
  with_items:
    - https://github.com/databus23/helm-diff
    - https://github.com/jkroepke/helm-secrets
