#!/bin/bash

rm ~/.irb_history 2>/dev/null
rm ~/.pry_history 2>/dev/null
rm ~/.python_history 2>/dev/null
rm ~/.config/htop/htoprc 2>/dev/null
rm ~/.rediscli_history 2>/dev/null
rm ~/.racket/racket-prefs.rktd 2>/dev/null
rm ~/.dbshell 2>/dev/null
rm ~/.scala_history 2>/dev/null
cp ~/.java/.userPrefs/tool/JShell/prefs.xml.bak ~/.java/.userPrefs/tool/JShell/prefs.xml 2>/dev/null
rm ~/.bash_history 2>/dev/null
history -c
powershell.exe -NoLogo -NoProfile -Command "Set-Clipboard -Value \$null"

echo "-cleanup: clear --all"

for dest in "$@"
do
  case "$dest" in
    "v")
      cat /dev/null > ~/.viminfo
      echo "v";;
    "vi")
      cat /dev/null > ~/.viminfo
      echo "vi";;
    "vim")
      cat /dev/null > ~/.viminfo
      echo "vim";;
    *)
      ;;
  esac
done
