- name: Set up workstation
  hosts: all
  connection: ssh
  roles:
    - role: dir
      tags:
        - dir
    - role: bash
      tags:
        bash
    - role: timezone
      tags:
        - timezone
    - role: iptables # THIS WILL FLUSH IPTABLES SETTINGS
      tags:
        - iptables
    - role: docker # update/upgrade apt
      tags:
        - docker
    - role: kubectl
      tags:
        - kubectl
    - role: helm
      tags:
        - helm
    - role: apt
      tags:
        - apt
    - role: git
      tags:
        - git
    - role: fzf
      tags:
        - fzf
    - role: rg
      tags:
        - rg
    - role: java
      tags:
        - java
    - role: python
      tags:
        - python
    - role: ruby
      tags:
        - ruby
    - role: node
      tags:
        - node
    - role: nvim
      tags:
        - nvim
    # - role: vim
    #   tags:
    #     - vim
    - role: go
      tags:
        - go
    - role: terraform
      tags:
        - terraform
    - role: tmux
      tags:
        - tmux
    - role: peco
      tags:
        - peco
    - role: bat
      tags:
        - bat
