#!/bin/bash

if [ "$1" == "restore" ]; then
  cat list.txt | awk '{print "cp", "./backup/"$1, $2}' | sh -x
else
  # echo "usage: ./install (install|restore)"
  if [ ! -d backup ]; then
    mkdir backup
  fi
  if [ ! -d ~/.peco ]; then
    mkdir ~/.peco
  fi
  cat list.txt | awk '{print "cp", $2, "./backup/"$1}' | sh -x
  cat list.txt | awk '{print "cp", "./original/"$1, $2}' | sh -x
  mkdir -p ~/.config/nvim/after
  rm -r ~/.config/nvim/after
  ln -s ~/.vim/after ~/.config/nvim/after
  gem install solargraph
  gem install tmuxinator
  gem install rufo
  sudo apt install bat
  sudo apt install fd-find
  sudo apt install shellcheck
  solargraph download-core
  # coursier {{{
  curl -fLo cs https://git.io/coursier-cli-"$(uname | tr LD ld)"
  chmod +x cs
  ./cs install cs
  ./cs install scalafmt
  rm cs
  # }}}
  echo "========================"
  echo ":CocInstall coc-metals"
  echo "set -o vi (/etc/bash.bashrc)"
fi
