#!/usr/bin/env bash
set -e

tags="$1"

if [ -z $tags ]; then
  tags="all"
fi

if ! [ -x "$(command -v ansible)" ]; then
  sudo apt update
  sudo apt -y install ansible
fi

ansible-playbook -i ./hosts ./dotfiles.yml --tags $tags

echo "dotfiles: Bootstrap complete"
echo "Successfully set up dev environment."
