- name: Install required system packages
  become: true
  apt:
    pkg:
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - python3-flake8
      - python3-yapf
    state: latest
    update_cache: yes

- name: update-alternatives install python3
  become: true
  community.general.alternatives:
    name: python
    path: /usr/bin/python3.12
    link: /usr/bin/python
    priority: "312"

- name: Set to auto python version
  become: true
  shell: update-alternatives --auto python
