- name: Add an apt signing key for Kubernetes
  become: true
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.asc
    mode: '0644'

- name: Add Kubernetes Repository
  become: true
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
    state: present
    filename: kubernetes

- name: Install Kubernetes
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubectl
