- name: Install git
  apt: name=git state=present
  become: true
  become_user: root
  become_method: sudo

- name: Install gitconfig
  template:
    src: "gitconfig.j2"
    dest: "~/.gitconfig"

- name: Install git commit template
  template:
    src: "tmpl.j2"
    dest: "~/.tmpl.md"
