- name: Set up workstation
  hosts: all
  roles:
    - role: dir
      tags:
        - dir
    - role: bash
      tags:
        bash
    - role: docker # update/upgrade apt
      tags:
        - docker
    - role: apt
      tags:
        - apt
    - role: git
      tags:
        - git
    - role: fzf
      tags:
        - fzf
    - role: python
      tags:
        - python
    - role: ruby
      tags:
        - ruby
