- name: Install rbenv
  shell:
    cmd: |
        rbenv init
        mkdir -p "$(rbenv root)"/plugins
        git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build || (git --git-dir "$(rbenv root)"/plugins/ruby-build/.git --work-tree "$(rbenv root)"/plugins/ruby-build fetch && git --git-dir "$(rbenv root)"/plugins/ruby-build/.git --work-tree "$(rbenv root)"/plugins/ruby-build reset --hard origin/master)
        git clone https://github.com/garnieretienne/rvm-download.git ~/.rbenv/plugins/rvm-download

- name: Install rbenv for root
  become: true
  shell:
    cmd: |
        rbenv init
        mkdir -p "$(rbenv root)"/plugins
        git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build || (git --git-dir "$(rbenv root)"/plugins/ruby-build/.git --work-tree "$(rbenv root)"/plugins/ruby-build fetch && git --git-dir "$(rbenv root)"/plugins/ruby-build/.git --work-tree "$(rbenv root)"/plugins/ruby-build reset --hard origin/master)
        git clone https://github.com/garnieretienne/rvm-download.git ~/.rbenv/plugins/rvm-download

# - name: Install ruby (x86_64)
#   shell:
#     cmd: |
#         rbenv download 3.2.3
#         rbenv global 3.2.3
#   when: ansible_architecture == "x86_64"

- name: Install ruby (aarch64)
  shell:
    cmd: |
        rbenv install 3.2.3
        rbenv global 3.2.3
  # when: ansible_architecture == "aarch64"

# - name: Install ruby for root (x86_64)
#   become: true
#   shell:
#     cmd: |
#         rbenv download 3.2.3
#         rbenv global 3.2.3
#   when: ansible_architecture == "x86_64"

- name: Install ruby for root (aarch64)
  become: true
  shell:
    cmd: |
        rbenv install 3.2.3
        rbenv global 3.2.3
  # when: ansible_architecture == "aarch64"

- name: Install gem
  shell:
    cmd: |
        $HOME/.rbenv/shims/gem install bundler pry pry-doc tmuxinator rufo ruby-lsp

- name: Install gem for root
  become: true
  shell:
    cmd: |
        /root/.rbenv/shims/gem install bundler pry pry-doc tmuxinator rufo ruby-lsp
