- name: Install rbenv/ruby
  shell:
    cmd: |
        rbenv init
        mkdir -p "$(rbenv root)"/plugins
        git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build || (git --git-dir "$(rbenv root)"/plugins/ruby-build/.git --work-tree "$(rbenv root)"/plugins/ruby-build fetch && git --git-dir "$(rbenv root)"/plugins/ruby-build/.git --work-tree "$(rbenv root)"/plugins/ruby-build reset --hard origin/master)
        rbenv install 3.3.0
        rbenv global 3.3.0

- name: Install rbenv/ruby for root
  become: true
  shell:
    cmd: |
        rbenv init
        mkdir -p "$(rbenv root)"/plugins
        git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build || (git --git-dir "$(rbenv root)"/plugins/ruby-build/.git --work-tree "$(rbenv root)"/plugins/ruby-build fetch && git --git-dir "$(rbenv root)"/plugins/ruby-build/.git --work-tree "$(rbenv root)"/plugins/ruby-build reset --hard origin/master)
        rbenv install 3.3.0
        rbenv global 3.3.0

- name: Install gem
  shell:
    cmd: |
        $HOME/.rbenv/shims/gem install bundler pry pry-doc tmuxinator rufo solargraph
#         $HOME/.rbenv/shims/solargraph download-core

- name: Install gem for root
  become: true
  shell:
    cmd: |
        /root/.rbenv/shims/gem install bundler pry pry-doc tmuxinator rufo solargraph
